# -*- snakemake -*-
# Snakefile for running analysis of data in Treutlein et al, 2014
import os
from snakemakelib.config import load_sml_config, SNAKEMAKELIB_PATH
from snakemakelib.bio.ngs.tools.sratools import register_metadata

SRAPROJECT = "SRP033209"
workdir: "."

# Load external configuration files
load_sml_config(config)

# Rule for creating sample directories and links. Here, sequence data
# is located one level up in folder hierarchy, in folder data
datadir = os.path.abspath("../data")
metadata = os.path.join(datadir, "{srp}_info.csv".format(srp=SRAPROJECT))

config = register_metadata(metadata, config)

include: os.path.join(SNAKEMAKELIB_PATH, "rules/bio/ngs/tools/sratools.rules")
include: os.path.join(SNAKEMAKELIB_PATH, "workflows/bio/scrnaseq.workflow")
